### ISSUE TITLE
🎨 Dashboard design

### ISSUE THREAD

**Issue by noyamirai** [noyamirai/cmd-online#10]

**Comment by Aidan98** [comment]
Shouldn't @TejoBurgboy also be an assignee to this issue, as he will be creating the dashboard🤔?

**Comment by Aidan98** [comment]
I added him just in case

**Comment by noyamirai** [comment]
> Shouldn't @TejoBurgboy also be an assignee to this issue, as he will be creating the dashboard🤔?

@Aidan98 hmm, no I rather create the design myself since I've designed all of the screens already 😅  That way everything will stay consistent as well

**Comment by noyamirai** [comment]
Here is the dashboard design (for students)! I know we already discussed the design in class but I am updating this issue with the design for documentation purposes hehe

<img width="894" alt="Screenshot 2022-03-25 at 16 56 19" src="https://user-images.githubusercontent.com/90140220/160156273-277b8654-360b-4d10-8f89-975b14f8b078.png">
