### ISSUE TITLE
🎨 Create account and login design

### ISSUE THREAD

**Issue by noyamirai** [noyamirai/cmd-online#11]

**Comment by noyamirai** [comment]
Hi guys (@Aidan98, @juliettegroot and @TejoBurgboy)! I made two simple designs for the login screen with the assets and styles we currently already have. I did not want to make it too 'fancy' or complicated since we do not have a lot of time to focus on design (if we have time left, we could review everything again). 

In the image below you can see the two versions I made, I would appreciate it if you could all take a look and tell me which version you prefer and whether or not you have other feedback/ideas regarding login/create account. 

_Note: I did not make create account design since it would basically have the same template/layout and styling as the login_

<img width="890" alt="Screenshot 2022-03-23 at 11 11 27" src="https://user-images.githubusercontent.com/90140220/159676652-bf81196c-bee6-4513-a3b3-913a20e59f29.png">

**Comment by Aidan98** [comment]
I like `v1` more than the other. `v2` is to yellow and as a result looks too cartoony (getting comic sans vibes😅), whereas `v1` has nice contrast and there is a clear separation between the banner and the content.

**Comment by Aidan98** [comment]
I'd like to be responsible for implementing whichever design we end up using.

**Comment by TejoBurgboy** [comment]
> I like `v1` more than the other. `v2` is to yellow and as a result looks too cartoony (getting comic sans vibes😅), whereas `v1` has nice contrast and there is a clear separation between the banner and the content.

same

**Comment by noyamirai** [comment]
> I'd like to be responsible for implementing whichever design we end up using.

Sure! Shouldn't be too hard since most of the styling is available in CSS already! So if you implement `v1` check out all the root variables/classes that are available! (example: `var(--border-settings)` and `var(--border-radius)`)
