### ISSUE TITLE
⚡ Account creation

### ISSUE THREAD

**Issue by noyamirai** [noyamirai/cmd-online#6]
Create account with the following user properties:

- E-mail: should end with '@hva.nl'
- Username: always unique
- Name: first, insertion, last
- Password
- Profile picture: users should be able to upload jpg or png files

When creating an account (aka inserting a new document into a collection), maybe you can reuse the CRUD operations I have written? For example:

```javascript
CRUD.createDocs(schemas.User, { required object properties })
.then((userObject) => {
       CRUD.createDoc(schemas.Student, { user: userObject.id, cmd_skills: { best: ["622a0cbb6df854b8951e7e55"], want_to_learn: ["622a0cbb6df854b8951e7e55"]}, classes: userObject.classes, courses: userObject.courses })
        .then((student) => {
            CRUD.addIdReferenceToDoc(schemas.Course, student.courses, "students", student.id);
            CRUD.addIdReferenceToDoc(schemas.Class, student.classes, "students", student.id);
        });
});
```

Lmk if you need help!

**Comment by Aidan98** [comment]
I've never used CRUD, but I'll check it out

**Comment by Aidan98** [comment]
> Create account with the following user properties:
> 
>     * E-mail: should end with '@hva.nl'
> 
>     * Username: always unique
> 
>     * Name: first, insertion, last
> 
>     * Password
> 
>     * Profile picture: users should be able to upload jpg or png files
> 
> 
What do you mean with "insertion"? @noyamirai  Do you mean a space between first name and last name; like this "Aidan Omwando" or have them separate "Aidan"  "Omwando"

**Comment by Aidan98** [comment]
I completed the task
