### ISSUE TITLE
⚡ Login

### ISSUE THREAD

**Issue by Aidan98** [noyamirai/cmd-online#9]
Feature: allow the user to login to CMD-online

**Comment by noyamirai** [comment]
Wasn't @juliettegroot supposed to work on the login? 🤔 If you would rather do it, since you made the create account feature already etc, maybe she could work on "changing profile/account details"?

**Comment by Aidan98** [comment]
Yeah, I thought it made sense to do both as I already have experience with Argon2 and route authentication
